# Generated by Django 3.2.12 on 2022-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_challengeachieve_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeachieve',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengeachieve',
            name='acheive_date',
            field=models.DateTimeField(blank=True, default=True, null=True),
        ),
    ]
