# Generated by Django 4.1 on 2022-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0003_auto_20220729_1403"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="tier",
            field=models.IntegerField(
                choices=[(0, "UNKNOWN"), (1, "BRONZE"), (2, "SILVER"), (3, "GOLD")],
                default=0,
            ),
            preserve_default=False,
        ),
    ]
