# Generated by Django 3.2.12 on 2022-07-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_account_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=200)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('receiver_read', models.BooleanField()),
                ('sender_delete', models.BooleanField()),
                ('receiver_delete', models.BooleanField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.account')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.account')),
            ],
        ),
    ]
