# Generated by Django 4.1.3 on 2023-07-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_account_github_id_alter_account_introduction_and_more'),
        ('message', '0002_alter_message_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('sender_name', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('receiver_read', models.BooleanField()),
                ('receiver_delete', models.BooleanField()),
                ('route_id', models.IntegerField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
            ],
        ),
    ]
