version: '3.8'
# Please Change the version oa image before deploying

services:
  ## Product
  FRONTEND:
    image: sosd/sosd-frontend-vitejs:v1.0.7
    container_name: sosd-frontend
    restart: always
    environment:
      VIRTUAL_HOST: 'sosd.skku.edu'
      LETSENCRYPT_HOST: 'sosd.skku.edu'
      VIRTUAL_PORT: 5173
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - 'net'
    ports:
      - '4401:5173'
  OSP:
    image: sosd/sosd-backend-django:v1.0.7
    container_name: sosd-backend
    restart: always
    volumes:
      - '/home/sosd-com/SKKU-OSP/osp/data/media:/app/data/media'
      - '/home/sosd-com/SKKU-OSP/osp/static:/app/staticfiles'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - 'net'
    ports:
      - '4402:8000'
  ## Dev
  # FRONTEND:
  #  image: sosd/sosd-frontend-vitejs:test
  #  container_name: sosd-frontend
  #  restart: always
  #  environment:
  #    VIRTUAL_HOST: "sosd-dev.skku.edu"
  #    LETSENCRYPT_HOST: "sosd-dev.skku.edu"
  #  extra_hosts:
  #    - host.docker.internal:host-gateway
  #  networks:
  #    - "net"
  #  ports:
  #    - "4401:5173"
  # OSP:
  #  image: sosd/sosd-backend-django:test
  #  container_name: sosd-backend
  #  restart: always
  #
  #  extra_hosts:
  #    - host.docker.internal:host-gateway
  #  networks:
  #    - "net"
  #  ports:
  #    - "4402:4402"

networks:
  net:
    external: true
