version: "3.8"
# Please Change the version oa image before deploying

services:
  ## Product
  FRONTEND:
    image: sosd/sosd-frontend-vitejs:test
    container_name: sosd-frontend
    restart: always
    environment:
      VIRTUAL_HOST: "sosd.skku.edu"
      LETSENCRYPT_HOST: "sosd.skku.edu"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - "net"
    ports:
      - "4401:5173"
  OSP:
    image: sosd/sosd-backend-django:test
    container_name: sosd-backend
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - "net"
    ports:
      - "4402:4402"
  ## Dev
  # FRONTEND:
  #  image: sosd/sosd-frontend-vitejs:test
  #  container_name: sosd-frontend
  #  restart: always
  #  environment:
  #    VIRTUAL_HOST: "sosd-dev.skku.edu"
  #    LETSENCRYPT_HOST: "sosd-dev.skku.edu"
  #  extra_hosts:
  #    - host.docker.internal:host-gateway
  #  networks:
  #    - "net"
  #  ports:
  #    - "4401:5173"
  # OSP:
  #  image: sosd/sosd-backend-django:test
  #  container_name: sosd-backend
  #  restart: always
  #
  #  extra_hosts:
  #    - host.docker.internal:host-gateway
  #  networks:
  #    - "net"
  #  ports:
  #    - "4402:4402"

networks:
  net:
    external: true
