# Generated by Django 3.2.12 on 2022-06-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='period_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='period_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='mod_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
