# Generated by Django 4.0.5 on 2022-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20220629_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='mod_date',
            new_name='del_date',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
