# Generated by Django 3.2.12 on 2022-06-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_githubscore'),
        ('community', '0002_auto_20220628_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.account'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.account'),
        ),
    ]
