# Generated by Django 3.2.12 on 2022-07-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_account_introduction'),
        ('community', '0003_rename_mod_date_articlecomment_del_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookmark_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.article')),
            ],
        ),
        migrations.AddConstraint(
            model_name='articlebookmark',
            constraint=models.UniqueConstraint(fields=('article', 'account'), name='unique_account_article_bookmark'),
        ),
    ]
