# Generated by Django 3.2.12 on 2022-07-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220727_1502'),
        ('community', '0006_board_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.article')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleBookmark',
        ),
        migrations.AddConstraint(
            model_name='articlescrap',
            constraint=models.UniqueConstraint(fields=('article', 'account'), name='unique_account_article_Scrap'),
        ),
    ]
