# Generated by Django 4.1.3 on 2023-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_rename_board_id_article_board_article_is_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='img/article/')),
                ('created_user', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('article_id', models.BigIntegerField()),
            ],
        ),
    ]
