# Generated by Django 4.1.3 on 2023-03-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='created_user',
            field=models.CharField(max_length=150),
        ),
    ]
