# Generated by Django 4.1.3 on 2023-03-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_articlefile_articleimage_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefile',
            name='filename',
            field=models.CharField(default='undefined', max_length=300),
        ),
    ]
