# Generated by Django 4.1.3 on 2023-07-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_articlefile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
