# Generated by Django 4.1.3 on 2023-07-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0006_alter_domainlayer_child_tag_and_more'),
        ('community', '0013_alter_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tagindependent'),
        ),
    ]
