# Generated by Django 4.1.3 on 2023-11-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0014_alter_articletag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="name",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
