# Generated by Django 4.1.3 on 2024-04-11 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_alter_board_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(default='1999-03-25')),
                ('thumbnail', models.FileField(default='1', upload_to='file/article/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.article')),
            ],
        ),
    ]
