# Generated by Django 4.1.3 on 2024-07-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_article_is_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroarticle',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
