# Generated by Django 4.0.5 on 2022-07-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_merge_0002_alter_team_image_0002_auto_20220712_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitemessage',
            name='is_apply',
        ),
        migrations.AddField(
            model_name='teaminvitemessage',
            name='direction',
            field=models.BooleanField(choices=[(True, 'TO_ACCOUNT'), (False, 'TO_TEAM')], default=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='img/team/default.jpg', upload_to='img/team/'),
        ),
        migrations.AlterField(
            model_name='teaminvitemessage',
            name='status',
            field=models.IntegerField(choices=[(0, '대기중'), (1, '승인'), (2, '거절')]),
        ),
    ]
