# Generated by Django 4.0.5 on 2022-07-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_teaminvitemessage_is_apply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaminvitemessage',
            old_name='target_account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='teaminvitemessage',
            old_name='target_team',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='teaminvitemessage',
            name='status',
            field=models.IntegerField(choices=[(0, '대기중'), (1, '승인'), (2, '거절')], default=0),
        ),
    ]
