# Generated by Django 2.2.12 on 2022-06-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubOverview',
            fields=[
                ('github_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('followings', models.IntegerField()),
                ('total_repos', models.IntegerField()),
                ('total_commits', models.IntegerField()),
                ('total_prs', models.CharField(db_column='total_PRs', max_length=45)),
                ('total_issues', models.CharField(max_length=45)),
                ('achievements', models.CharField(blank=True, max_length=200, null=True)),
                ('highlights', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'github_overview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTab',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=45)),
                ('dept', models.CharField(max_length=45)),
                ('github_id', models.CharField(max_length=40)),
                ('absence', models.IntegerField()),
                ('plural_major', models.IntegerField()),
                ('personal_email', models.CharField(max_length=100)),
                ('primary_email', models.CharField(max_length=100)),
                ('secondary_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'student_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GithubStatsYymm',
            fields=[
                ('github_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('start_yymm', models.DateField()),
                ('end_yymm', models.DateField()),
                ('stars', models.IntegerField()),
                ('num_of_cr_repos', models.IntegerField()),
                ('num_of_co_repos', models.IntegerField()),
                ('num_of_commits', models.IntegerField()),
                ('num_of_prs', models.IntegerField(db_column='num_of_PRs')),
                ('num_of_issues', models.IntegerField()),
            ],
        ),
    ]
