# Generated by Django 3.2.12 on 2022-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('github_id', models.CharField(max_length=40)),
                ('total_score', models.FloatField()),
                ('commit_cnt', models.IntegerField()),
                ('commit_line', models.IntegerField()),
                ('issue_cnt', models.IntegerField()),
                ('pr_cnt', models.IntegerField()),
                ('repo_cnt', models.IntegerField()),
                ('dept', models.CharField(max_length=45)),
                ('absence', models.IntegerField()),
                ('plural_major', models.IntegerField()),
            ],
            options={
                'db_table': 'score_table_sum',
                'managed': False,
            },
        ),
    ]
