# Generated by Django 3.2.12 on 2022-06-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_scoretable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('student_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.studenttab')),
            ],
        ),
    ]
