# Generated by Django 3.2.12 on 2022-06-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['student_data']},
        ),
        migrations.AlterModelOptions(
            name='studenttab',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
