# Generated by Django 4.0.5 on 2022-07-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220706_1126'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='githubstatsyymm',
            table='github_stats_yymm',
        ),
    ]
