# Generated by Django 3.2.13 on 2022-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_accountinterest_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
