# Generated by Django 3.2.12 on 2022-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_account_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='recommend_open',
            field=models.BooleanField(default=False),
        ),
    ]
