# Generated by Django 3.2.12 on 2022-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220727_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepoContributor',
            fields=[
                ('github_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(max_length=40)),
                ('repo_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'github_repo_contributor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GithubUserFollowing',
            fields=[
                ('github_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('following_id', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'github_user_following',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GithubUserStarred',
            fields=[
                ('github_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('starred_repo_owner', models.CharField(max_length=40)),
                ('starred_repo_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'github_user_starred',
                'managed': False,
            },
        ),
    ]
