# Generated by Django 4.0.5 on 2022-08-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_githubrepocontributor_githubuserfollowing_githubuserstarred'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeA1', models.IntegerField()),
                ('typeA2', models.IntegerField()),
                ('typeB1', models.IntegerField()),
                ('typeB2', models.IntegerField()),
                ('typeC1', models.IntegerField()),
                ('typeC2', models.IntegerField()),
                ('typeD1', models.IntegerField()),
                ('typeD2', models.IntegerField()),
                ('typeE1', models.IntegerField()),
                ('typeE2', models.IntegerField()),
                ('typeG1', models.IntegerField()),
                ('typeG2', models.IntegerField()),
                ('typeF1', models.IntegerField()),
                ('typeF2', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
            ],
        ),
    ]
