# Generated by Django 3.2.13 on 2022-08-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220802_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devtype',
            old_name='typeA1',
            new_name='typeA',
        ),
        migrations.RenameField(
            model_name='devtype',
            old_name='typeA2',
            new_name='typeB',
        ),
        migrations.RenameField(
            model_name='devtype',
            old_name='typeB1',
            new_name='typeC',
        ),
        migrations.RenameField(
            model_name='devtype',
            old_name='typeB2',
            new_name='typeD',
        ),
        migrations.RenameField(
            model_name='devtype',
            old_name='typeC1',
            new_name='typeE',
        ),
        migrations.RenameField(
            model_name='devtype',
            old_name='typeC2',
            new_name='typeF',
        ),
        migrations.RenameField(
            model_name='devtype',
            old_name='typeD1',
            new_name='typeG',
        ),
        migrations.RemoveField(
            model_name='devtype',
            name='typeD2',
        ),
        migrations.RemoveField(
            model_name='devtype',
            name='typeE1',
        ),
        migrations.RemoveField(
            model_name='devtype',
            name='typeE2',
        ),
        migrations.RemoveField(
            model_name='devtype',
            name='typeF1',
        ),
        migrations.RemoveField(
            model_name='devtype',
            name='typeF2',
        ),
        migrations.RemoveField(
            model_name='devtype',
            name='typeG1',
        ),
        migrations.RemoveField(
            model_name='devtype',
            name='typeG2',
        ),
    ]
