# Generated by Django 3.2.12 on 2022-08-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220805_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='student_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.studenttab'),
        ),
    ]
