# Generated by Django 4.0.5 on 2022-09-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_account_student_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubRepoCommits',
        ),
        migrations.DeleteModel(
            name='GithubRepoStats',
        ),
        migrations.DeleteModel(
            name='ScoreTable',
        ),
    ]
