# Generated by Django 4.0.5 on 2022-09-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_delete_githubrepocommits_delete_githubrepostats_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubRepoContributor',
        ),
    ]
