# Generated by Django 4.0.6 on 2022-10-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_delete_githubrepocontributor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountinterest',
            constraint=models.UniqueConstraint(fields=('account', 'tag'), name='accountbytag'),
        ),
    ]
