# Generated by Django 4.0.5 on 2022-10-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_accountinterest_accountbytag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(default='img/profile_img/default.jpg', upload_to='img/profile_img'),
        ),
    ]
