# Generated by Django 4.1 on 2022-11-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_account_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPrivacy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_lvl', models.IntegerField(default=0)),
                ('is_write', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
            ],
        ),
    ]
