# Generated by Django 4.1.3 on 2023-03-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_tagindependent'),
        ('user', '0022_githubscoretable_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinterest',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tagindependent'),
        ),
    ]
