# Generated by Django 4.1.3 on 2023-04-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_accountinterest_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githuboverview',
            options={},
        ),
    ]
