# Generated by Django 4.1.3 on 2023-04-11 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_githuboverview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='githuboverview',
            name='contributed_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='githuboverview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githuboverview',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
