# Generated by Django 4.1.3 on 2023-04-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_githuboverview_contributed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githuboverview',
            old_name='contributed_date',
            new_name='github_updated_date',
        ),
    ]
