# Generated by Django 4.1.3 on 2023-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_rename_contributed_date_githuboverview_github_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='githuboverview',
            name='crawled_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
