# Generated by Django 4.1.3 on 2023-10-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0029_alter_account_github_id_alter_account_introduction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devtype",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.account"
            ),
        ),
    ]
