# Generated by Django 4.1.3 on 2023-10-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_devtype_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtype',
            name='typeA',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devtype',
            name='typeB',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devtype',
            name='typeC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devtype',
            name='typeD',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devtype',
            name='typeE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devtype',
            name='typeF',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devtype',
            name='typeG',
            field=models.IntegerField(default=0),
        ),
    ]
