# Generated by Django 4.1.3 on 2024-07-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_githuboverview_achievements_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qna',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
