# Generated by Django 4.1.3 on 2024-07-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_qna_solved_alter_qna_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnAImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='qna_images/')),
                ('image_name', models.CharField(max_length=255)),
                ('image_size', models.IntegerField()),
                ('qna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.qna')),
            ],
        ),
    ]
