# Generated by Django 4.1.3 on 2024-07-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_rename_image_qnaimage_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qnaimage',
            name='size',
        ),
    ]
