# Generated by Django 4.1.3 on 2024-07-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_remove_qnaimage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
