# Generated by Django 4.1.3 on 2025-07-15 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_qna_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('student_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField()),
                ('role', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=45)),
                ('dept', models.CharField(max_length=45)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(default='img/profile_img/default.jpg', upload_to='img/profile_img')),
                ('introduction', models.TextField(blank=True, default='', null=True)),
                ('portfolio', models.TextField(blank=True, default='', null=True)),
                ('plural_major', models.IntegerField()),
                ('absence', models.IntegerField()),
            ],
            options={
                'verbose_name': '유저 정보',
                'verbose_name_plural': '유저 정보',
                'db_table': 'test_user_account',
            },
        ),
        migrations.CreateModel(
            name='GithubAccount',
            fields=[
                ('github_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('github_login', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('github_name', models.CharField(blank=True, max_length=255, null=True)),
                ('github_token', models.CharField(blank=True, max_length=255, null=True)),
                ('last_crawling', models.DateTimeField(blank=True, null=True)),
                ('github_email', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='user.useraccount')),
            ],
            options={
                'verbose_name': '깃허브 계정',
                'verbose_name_plural': '깃허브 계정',
                'db_table': 'test_github_account',
            },
        ),
    ]
