# Generated by Django 4.1.3 on 2024-08-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_qna_response'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='user_account',
        ),
    ]
