# Generated by Django 3.2.12 on 2022-06-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageExtension',
            fields=[
                ('ext', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
        ),
        migrations.CreateModel(
            name='DomainLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tag', to='tag.tag')),
                ('parent_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tag', to='tag.tag')),
            ],
        ),
    ]
