# Generated by Django 4.1.3 on 2023-01-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='logo',
            field=models.FilePathField(default='default.svg', path=['C:\\Users\\user\\OneDrive\\Documents\\SKKU-OSP\\osp\\static']),
        ),
    ]
