# Generated by Django 4.1.3 on 2023-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_tag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagIndependent',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('logo', models.FilePathField(default='default.svg', path=['C:\\Users\\user\\OneDrive\\Documents\\SKKU-OSP\\osp\\static'])),
                ('color', models.CharField(default='#D3D3D3', max_length=10)),
            ],
        ),
    ]
