# Generated by Django 4.1.3 on 2023-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_tagindependent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='logo',
            field=models.FilePathField(default='default.svg', path=['C:\\Users\\ssaje\\Desktop\\SKKU-OSP\\osp\\static']),
        ),
        migrations.AlterField(
            model_name='tagindependent',
            name='logo',
            field=models.FilePathField(default='default.svg', path=['C:\\Users\\ssaje\\Desktop\\SKKU-OSP\\osp\\static']),
        ),
    ]
