# Generated by Django 4.1.3 on 2023-07-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0005_alter_tag_logo_alter_tagindependent_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainlayer',
            name='child_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tag', to='tag.tagindependent'),
        ),
        migrations.AlterField(
            model_name='domainlayer',
            name='parent_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tag', to='tag.tagindependent'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='logo',
            field=models.CharField(default='default.svg', max_length=200),
        ),
        migrations.AlterField(
            model_name='tagindependent',
            name='logo',
            field=models.CharField(default='default.svg', max_length=200),
        ),
    ]
