# Generated by Django 4.1.3 on 2023-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubStars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_id', models.CharField(max_length=40)),
                ('repo_name', models.CharField(max_length=100)),
                ('github_id', models.CharField(max_length=40)),
                ('stargazer', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'github_stars',
                'unique_together': {('owner_id', 'repo_name', 'stargazer')},
            },
        ),
    ]
