# Generated by Django 4.1.3 on 2024-08-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_githubstars'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepoCommitFiles',
            fields=[
                ('github_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=100)),
                ('sha', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=40)),
                ('additions', models.IntegerField()),
                ('deletions', models.IntegerField()),
            ],
            options={
                'db_table': 'github_repo_commit_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GithubRepoStatsyymm',
            fields=[
                ('github_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=100)),
                ('start_yymm', models.DateField()),
                ('end_yymm', models.DateField()),
                ('stargazers_count', models.IntegerField(blank=True, null=True)),
                ('forks_count', models.IntegerField(blank=True, null=True)),
                ('commits_count', models.IntegerField(blank=True, null=True)),
                ('prs_count', models.IntegerField(blank=True, null=True)),
                ('open_issue_count', models.IntegerField(blank=True, null=True)),
                ('close_issue_count', models.IntegerField(blank=True, null=True)),
                ('watchers_count', models.IntegerField(blank=True, null=True)),
                ('dependencies', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=45, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('contributors_count', models.IntegerField(blank=True, null=True)),
                ('release_ver', models.CharField(blank=True, max_length=45, null=True)),
                ('release_count', models.IntegerField(blank=True, null=True)),
                ('readme', models.IntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=45, null=True)),
                ('proj_short_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'github_repo_stats_yymm',
                'managed': False,
            },
        ),
    ]
