# Generated by Django 4.1.3 on 2025-06-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_githubstars'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepoCommitFiles',
            fields=[
                ('github_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=100)),
                ('sha', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=40)),
                ('additions', models.IntegerField()),
                ('deletions', models.IntegerField()),
            ],
            options={
                'db_table': 'github_repo_commit_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GithubRepoStatsyymm',
            fields=[
                ('github_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=100)),
                ('start_yymm', models.DateField()),
                ('end_yymm', models.DateField()),
                ('stargazers_count', models.IntegerField(blank=True, null=True)),
                ('forks_count', models.IntegerField(blank=True, null=True)),
                ('commits_count', models.IntegerField(blank=True, null=True)),
                ('prs_count', models.IntegerField(blank=True, null=True)),
                ('open_issue_count', models.IntegerField(blank=True, null=True)),
                ('close_issue_count', models.IntegerField(blank=True, null=True)),
                ('watchers_count', models.IntegerField(blank=True, null=True)),
                ('dependencies', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=45, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('contributors_count', models.IntegerField(blank=True, null=True)),
                ('release_ver', models.CharField(blank=True, max_length=45, null=True)),
                ('release_count', models.IntegerField(blank=True, null=True)),
                ('readme', models.IntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=45, null=True)),
                ('proj_short_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'github_repo_stats_yymm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestGithubRepository',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=100)),
                ('github_id', models.CharField(max_length=40)),
                ('stars', models.IntegerField(default=0)),
                ('watchers', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('commits', models.IntegerField(default=0)),
                ('commit_del', models.IntegerField(default=0)),
                ('commit_add', models.IntegerField(default=0)),
                ('commit_line', models.IntegerField(default=0)),
                ('pr', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('closed_issues', models.IntegerField(default=0)),
                ('dependencies', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('readme', models.BooleanField(default=False)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('commit_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('contributors', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'test_github_repository',
            },
        ),
    ]
