# Generated by Django 4.1.3 on 2025-06-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_githubrepocommitfiles_githubrepostatsyymm_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testgithubrepository',
            constraint=models.UniqueConstraint(fields=('owner_name', 'repo_name', 'github_id'), name='unique_owner_repo_github_id'),
        ),
        migrations.AlterModelTable(
            name='testgithubrepository',
            table=None,
        ),
    ]
