# Generated by Django 4.1.3 on 2026-04-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_githubrepocommitfiles_githubrepostatsyymm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepoaievaluation',
            name='readme_missing_essentials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubrepoaievaluation',
            name='readme_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='githubrepoaievaluation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
