# Generated by Django 4.1.3 on 2025-06-29 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_testgithubrepository_unique_owner_repo_github_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testgithubrepository',
            table='test_github_repository',
        ),
    ]
