# Generated by Django 4.1.3 on 2025-07-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_alter_testgithubrepository_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGithubPullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_owner_id', models.CharField(max_length=40)),
                ('repo_name', models.CharField(max_length=100)),
                ('pr_number', models.IntegerField()),
                ('github_id', models.CharField(max_length=40)),
                ('pr_title', models.CharField(max_length=256)),
                ('pr_date', models.DateField()),
            ],
            options={
                'db_table': 'test_github_pull_request',
            },
        ),
        migrations.AddConstraint(
            model_name='testgithubpullrequest',
            constraint=models.UniqueConstraint(fields=('repo_owner_id', 'repo_name', 'pr_number'), name='unique_github_pull_request'),
        ),
    ]
