# Generated by Django 5.2.16 on 2026-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_githubrepoaievaluation_readme_criteria_scores_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='githubissues',
            table='v_github_issues',
        ),
        migrations.AlterModelTable(
            name='githubpulls',
            table='v_github_pulls',
        ),
        migrations.AlterModelTable(
            name='githubrepocommits',
            table='v_github_repo_commits',
        ),
        migrations.AlterModelTable(
            name='githubrepocontributor',
            table='v_github_repo_contributor',
        ),
        migrations.AlterModelTable(
            name='githubrepostats',
            table='v_github_repo_stats',
        ),
        migrations.CreateModel(
            name='GithubPrAiEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(max_length=40)),
                ('repo_name', models.CharField(max_length=100)),
                ('pr_number', models.IntegerField()),
                ('pr_score', models.CharField(blank=True, max_length=10, null=True)),
                ('pr_strengths', models.JSONField(blank=True, null=True)),
                ('pr_improvements', models.JSONField(blank=True, null=True)),
                ('pr_advice', models.JSONField(blank=True, null=True)),
                ('pr_missing', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'github_pr_ai_evaluation',
                'unique_together': {('github_id', 'repo_name', 'pr_number')},
            },
        ),
    ]
