# Generated by Django 4.1.3 on 2025-07-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_testgithubpullrequest_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testgithubpullrequest',
            name='unique_github_pull_request',
        ),
        migrations.RenameField(
            model_name='testgithubpullrequest',
            old_name='github_id',
            new_name='author_name',
        ),
        migrations.AlterField(
            model_name='testgithubpullrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
