# Generated by Django 4.1.3 on 2025-07-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_remove_testgithubpullrequest_unique_github_pull_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgithubpullrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
