# Generated by Django 4.1.3 on 2025-07-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_alter_testgithubpullrequest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGithubIssue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repo_owner_id', models.CharField(max_length=40)),
                ('repo_name', models.CharField(max_length=100)),
                ('issue_number', models.IntegerField()),
                ('author_name', models.CharField(max_length=40)),
                ('issue_title', models.CharField(max_length=256)),
                ('issue_date', models.DateField()),
            ],
            options={
                'db_table': 'test_github_issue',
            },
        ),
    ]
