# Generated by Django 3.2.12 on 2022-06-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualOverview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_num', models.IntegerField()),
                ('score', models.TextField()),
                ('score_diff', models.TextField()),
                ('score_sum', models.TextField()),
                ('score_std', models.TextField()),
                ('score_std_diff', models.TextField()),
                ('score_std_sum', models.TextField()),
                ('commit', models.TextField()),
                ('commit_std', models.TextField()),
                ('star', models.TextField()),
                ('star_std', models.TextField()),
                ('pr', models.TextField()),
                ('pr_std', models.TextField()),
                ('issue', models.TextField()),
                ('issue_std', models.TextField()),
                ('fork', models.TextField()),
                ('fork_std', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnnualTotal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_num', models.IntegerField()),
                ('student_KP', models.TextField()),
                ('student_KP_diff', models.TextField(default='[0, 0, 0]')),
                ('student_KP_sum', models.TextField(default='[0, 0, 0]')),
                ('student_total', models.TextField(default='[1, 1, 1]')),
                ('commit', models.TextField()),
                ('star', models.TextField()),
                ('repo', models.TextField()),
                ('repo_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DistFactor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_num', models.IntegerField()),
                ('year', models.IntegerField()),
                ('factor', models.CharField(max_length=10)),
                ('value', models.TextField()),
                ('value_sid', models.TextField()),
                ('value_sid_std', models.TextField()),
                ('value_sid_pct', models.TextField()),
                ('value_dept', models.TextField()),
                ('value_dept_std', models.TextField()),
                ('value_dept_pct', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DistScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_num', models.IntegerField()),
                ('year', models.IntegerField()),
                ('score', models.TextField()),
                ('score_diff', models.TextField()),
                ('score_sum', models.TextField()),
                ('score_sid', models.TextField()),
                ('score_sid_diff', models.TextField()),
                ('score_sid_sum', models.TextField()),
                ('score_sid_std', models.TextField()),
                ('score_sid_std_diff', models.TextField()),
                ('score_sid_std_sum', models.TextField()),
                ('score_sid_pct', models.TextField(default='[[],[],[],[],[],[],[]]')),
                ('score_sid_pct_diff', models.TextField(default='[[],[],[],[],[],[],[]]')),
                ('score_sid_pct_sum', models.TextField(default='[[],[],[],[],[],[],[]]')),
                ('score_dept', models.TextField()),
                ('score_dept_diff', models.TextField()),
                ('score_dept_sum', models.TextField()),
                ('score_dept_std', models.TextField()),
                ('score_dept_std_diff', models.TextField()),
                ('score_dept_std_sum', models.TextField()),
                ('score_dept_pct', models.TextField(default='[[],[],[]]')),
                ('score_dept_pct_diff', models.TextField(default='[[],[],[]]')),
                ('score_dept_pct_sum', models.TextField(default='[[],[],[]]')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('owner', models.CharField(max_length=40)),
                ('repo_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('github_id', models.CharField(max_length=40)),
                ('absence', models.IntegerField()),
                ('plural_major', models.IntegerField()),
                ('score', models.CharField(max_length=10)),
                ('score_diff', models.CharField(default='0.0', max_length=10)),
                ('score_sum', models.CharField(default='0.0', max_length=10)),
                ('commit', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('pr', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
                ('fork', models.IntegerField(default=0)),
            ],
        ),
    ]
