# Generated by Django 4.0.5 on 2022-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_annualoverview_fork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualoverview',
            name='class_num',
            field=models.TextField(default='[10, 5, 5, 5, 5]'),
        ),
        migrations.AddField(
            model_name='annualoverview',
            name='level_step',
            field=models.TextField(default='[0.5, 100, 2, 5, 2]'),
        ),
    ]
