name: 개발 서버 자동 배포

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Frontend Docker Image
        run: |
          cd frontend
          docker build --tag sosd/sosd-frontend-vitejs:test .

      - name: Build Backend Docker Image
        run: |
          cd osp
          docker build --tag sosd/sosd-backend-django:test .

      - name: Restart Docker Compose
        run: |
          cd ..
          docker-compose down
          docker-compose up -d
